name: Build LaTeX document
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        id: compile_latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
